# Generated by Django 4.1.7 on 2023-03-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='age',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
